### ISSUE TITLE
:sparkles: Have less verbose logs

### ISSUE THREAD

**Issue by CChemin** [InseeFr/sugoi-api#448]
In my opinion, there is too much logs of Info level, maybe pass it to Debug level ?

**Comment by mehdimaaref7** [comment]
As long as we only need the debug level in the console (that will catch the ERROR log messages directly in console), we can set the debug level in the console (properties). But for the log stored in applishare, maybe we keep the INFO Level in case there is a major bug, and we need to look closely, what do you think ?

**Comment by clement-dufaure** [comment]
INFO level should at least contains audit log (who made what, error/success), Should SugoiEventLogProducer be the only component to log audit log ?
So, other classes that sugoieventlogproducer :
- direct log warn and error
- dont log audit but send an event (or should duplicate in case of different log files ?)
- anithing else in debug -> anyone has exemple against this ?
