### ISSUE TITLE
:bug: Inconsistency between get all groups and get one group

### ISSUE THREAD

**Issue by CChemin** [InseeFr/sugoi-api#451]
Getting all groups have less restrictive filtering rules than getting one particular group on ldap reader store.

For instance, I have a user uid=toto where my Tourisme2 applications are stored.

`GET /realm/SSP/applications/Tourisme2` result in having all my applications plus toto_Tourisme2 which we shouldn't retrieve

`GET /realms/SSP/applications/Tourisme2/groups/toto_Tourisme2` result in a 404 error

(but maybe this can be fixed via better realm configuration)

**Comment by clement-dufaure** [comment]
add a filter by objectclass in properties and realm configuration  (objectclass=groupofuniquenames)
