### ISSUE TITLE
:bug: WebHookProducer should not be used when using a JMS Store

### ISSUE THREAD

**Issue by CChemin** [InseeFr/sugoi-api#601]
If a call like reset_password or change_password is used while a JMSWriterStore is configured the event triggering the WebHookProducer is send both in the first instance and in the instance receiving the JMS message leading to a redundant call to the WebHook.
The WebHookProducer cannot be systematically disabled with a JMSWriterStore since send_login does not use a writerstore

**Comment by CChemin** [comment]
as we don't want to link store type with webhook behavior an replacement issue may be to disable webhookproducer when we want to but this imply using send_login through a WriterStore.
Unless someone as an other idea ?

**Comment by micedre** [comment]
A miminal solution could be to exclude some events from event manager. Having a property for each event manager to exclude some events could resolve the issue here.

**Comment by CChemin** [comment]
ok for this solution. This issue is closed and replaced by #605
