### ISSUE TITLE
:speech_balloon: Is it ok that a userstorage writer can modify all users and thus add app managed properties ?

### ISSUE THREAD

**Issue by CChemin** [InseeFr/sugoi-api#616]
As a Sugoi user only having a writer role on a userstorage in a realm (let say ROLE_REALM1_US1_WRITER), I can create users with all properties that I want. It is also permitted for me to add properties that are seen as app managed properties and thus can be used for application to give rights (on the contrary it is not possible for me to add group).
Is this behaviour ok ? it means that if we want to let a person create users in a non sensitive userstorage, it can affect sensitive applications used in other userstorages when they rely on app managed properties.

**Comment by micedre** [comment]
We should change the permission model to introduce : 
* a realm administrator with all rights on all items (realm/us/apps) and later on the realm configuration
* a realm writer or user storage writer with only rights on users except on passwords and app-managed attributes
* a realm  app manager
* ......
