### ISSUE TITLE
:sparkles: Connection to ldap should have a timeout property

### ISSUE THREAD

**Issue by CChemin** [InseeFr/sugoi-api#844]
By default request on the directory timeout after 300000 ms. We want it to be modifiable.
This can be done by passing LDAPConnectionOptions in the creation of connections in LdapFactory and passing this option https://docs.ldap.com/ldap-sdk/docs/javadoc/com/unboundid/ldap/sdk/LDAPConnectionOptions.html#PROPERTY_DEFAULT_RESPONSE_TIMEOUT_MILLIS

**Comment by Ragatzino** [comment]
Added in https://github.com/InseeFr/sugoi-api/pull/845
